version: '3'

tasks:
  build:
    cmds:
      - go build -v main.go
    sources:
      - ./*.go
  dev:
    cmds:
      - air
  fmt:
    cmds:
      - go fmt ./...
  migrate:
    cmds:
      - migrate  -database postgresql://postgres:postgres@127.0.0.1:/postgres?sslmode=disable -path db/migrations/ up
