version: '3'

tasks:
  build:
    cmds:
      - go build -o tmp -v cmd/main.go
    sources:
      - ./*.go
  dev:
    cmds:
      - cmd: kill -9 $(lsof -t -i:1323)
        ignore_error: true
      - go run cmd/main.go
    env:
      RUN_ENV: Development
    sources:
      - ./**/*
  fmt:
    cmds:
      - go fmt ./...
  migrate:
    cmds:
      - migrate  -database postgresql://postgres:postgres@127.0.0.1:/postgres?sslmode=disable -path db/migrations/ up
